server:
  port: 8801

spring:
  application:
    name: cloud-stream-provider
  cloud:
    stream:
      binders:
        defaultRabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 192.168.203.129
                port: 5672
                username: admin
                password: admin123
      bindings:
        output:
          destination: studeExchange
          content-type: application/json
      binder: defaultRabbit
#  rabbitmq:
#    host: 192.168.203.129
#    username: admin
#    password: admin123
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 5
    instance-id: send-8801.com
    prefer-ip-address: true

